name: SENEX_DATASUS
channels: 
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib-base
  - jupyter
  - pySUS=0.5.8
  - geopandas
  - dython
  - seaborn
  - scipy
  - statsmodels
  - tsfresh
  - minepy
  - plotly